import type { DifficultySet, GameSettings, SaveData } from './types';

const base = {
  playerTurnLerp: 0.2,
  reactionSmoothing: 0.9,
  graceSecondsAfterRespawn: 2,
  extraLifeScoreStep: 1000,
};

export const difficulties: DifficultySet = {
  easy: {
    key: 'easy',
    label: 'Easy',
    scoreMultiplier: 0.85,
    startingLives: 6,
    playerSpeed: 210,
    playerHitboxScale: 0.78,
    enemyHitboxScale: 0.92,
    preySpawnPerSecond: 2.4,
    predatorSpawnPerSecond: 0.35,
    apexSpawnPerSecond: 0.05,
    hazardSpawnPerSecond: 0.03,
    maxPrey: 14,
    maxPredators: 2,
    maxApex: 1,
    maxHazards: 1,
    predatorAggression: 0.3,
    apexAggression: 0.5,
    apexMaxHealth: 2,
    apexTailHitLeniency: 1.18,
    ...base,
  },
  normal: {
    key: 'normal',
    label: 'Normal',
    scoreMultiplier: 1,
    startingLives: 5,
    playerSpeed: 220,
    playerHitboxScale: 0.84,
    enemyHitboxScale: 1,
    preySpawnPerSecond: 2.3,
    predatorSpawnPerSecond: 0.55,
    apexSpawnPerSecond: 0.08,
    hazardSpawnPerSecond: 0.05,
    maxPrey: 13,
    maxPredators: 3,
    maxApex: 1,
    maxHazards: 1,
    predatorAggression: 0.45,
    apexAggression: 0.65,
    apexMaxHealth: 3,
    apexTailHitLeniency: 1.05,
    ...base,
  },
  hard: {
    key: 'hard',
    label: 'Hard',
    scoreMultiplier: 1.25,
    startingLives: 4,
    playerSpeed: 228,
    playerHitboxScale: 0.9,
    enemyHitboxScale: 1.06,
    preySpawnPerSecond: 2.0,
    predatorSpawnPerSecond: 0.8,
    apexSpawnPerSecond: 0.12,
    hazardSpawnPerSecond: 0.08,
    maxPrey: 12,
    maxPredators: 4,
    maxApex: 2,
    maxHazards: 1,
    predatorAggression: 0.62,
    apexAggression: 0.82,
    apexMaxHealth: 4,
    apexTailHitLeniency: 0.92,
    ...base,
  },
};

export const defaultSettings: GameSettings = {
  soundEnabled: true,
  musicEnabled: false,
  hapticsEnabled: true,
  reducedMotion: false,
  controlMode: 'joystick',
};

export const defaultSaveData: SaveData = {
  version: 1,
  selectedMode: 'arcade',
  selectedDifficulty: 'normal',
  settings: defaultSettings,
  highScores: { easy: 0, normal: 0, hard: 0 },
  stats: {
    runsStarted: 0,
    totalDeaths: 0,
    totalPlaySeconds: 0,
    totalPreyEaten: 0,
    bestSizeTier: 1,
  },
  meta: {
    highestMilestone: 0,
    totalRuns: 0,
  },
  campaign: {
    unlockedStage: 1,
    completedStage: 0,
    starsByStage: {},
  },
  challenges: {
    completedIds: [],
    bestById: {},
    dailyStreak: 0,
  },
};
